### ISSUE TITLE
Disabling message "Metric: [metric]; Comparing x vectors"

### ISSUE THREAD

**Issue by jesi-rgb** [drostlab/philentropy#25]
Hello, droslab! First, thanks for such a thoughtful and carefully written job on this library. 

My only problem with the library is the output

`Metric: [metric]; Comparing x vectors.`

which in my particular case says 

`Metric: 'euclidean'; Comparing 2 vectors.`

Since I am doing so many comparisons, the output gets populated with this message thousands of times and it is difficult to read the actual output I am trying to come up with. I have tried searching the web for a "verbose" or "quiet" option to disable these logs, but found nothing. 

Maybe I didn't search enough, but would love to know if there is already a solution to this problem I have not found, or if it could be implemented.

Thank you very much in advance and have a nice day. Stay safe out there!

**Comment by HajkD** [comment]
Hi Jesús,

I am very happy to hear that you enjoy working with `philentropy` :)

When you install the developer version of `philentropy` directly from GitHub, then
you will find a new argument `mute_message` that you can set to `TRUE`.

```r
philentropy::distance(rbind(1:10 / sum(1:10), 20:29 / sum(20:29)),
                      method = "euclidean",
                      mute_message = TRUE)
```
```
euclidean 
0.1280713 
```

Alternatively, you can also always use the `suppressMessages(distance(...))` function to suppress message calls.

Does this solve your issue?

Best wishes,
Hajk

**Comment by jesi-rgb** [comment]
Hey, Hajk! Thank you very much for your quick and friendly answer!

Currently I am running the CRAN version of the library, but will for sure try the Github one once I finish the project.

On the other hand, I am still a newbie working with R and didn't know about the supressMessages function, but works flawlessly. So thank you so much for that piece of advice!

Again, thanks for this awesome response and have a nice day!
