### ISSUE TITLE
Distances.Rmd statement

### ISSUE THREAD

**Issue by Nowosad** [drostlab/philentropy#30]
Hi @HajkD, while working on the new vignette, I read the old ones. The `Distances.Rmd` one states:
>As you can see, although the `distance()` function is quite fast, the internal checks cause it to be 2x slower than the base `dist()` function (for the `euclidean` example). Nevertheless, in case you need to implement a faster version of the corresponding distance measure you can type `philentropy::` and then `TAB` allowing you to select the base distance computation functions (written in C++), e.g. `philentropy::euclidean()` which is almost 3x faster than the base `dist()` function.

I have done some testing, and to my surprise, the above statement is not universally true (at least for larger vectors). `distance()` and `euclidean()` have similar performances for larger vectors, and are slower than `dist()`. This is not an issue - I just wanted to let you know. Feel free to close this issue after reading this message.

``` r
# install.packages("microbenchmark")
library(philentropy)
library(microbenchmark)

# define a probability density function P
P <- 1:10/sum(1:10)
# define a probability density function Q
Q <- 20:29/sum(20:29)

# combine P and Q as matrix object
x <- rbind(P,Q)

microbenchmark(
  distance(x,method = "euclidean", test.na = FALSE, mute.message = TRUE),
  dist(x,method = "euclidean"),
  euclidean(x[1 , ], x[2 , ], FALSE)
)
#> Unit: microseconds
#>                                                                     expr    min
#>  distance(x, method = "euclidean", test.na = FALSE, mute.message = TRUE) 20.853
#>                                            dist(x, method = "euclidean") 14.009
#>                                         euclidean(x[1, ], x[2, ], FALSE)  4.299
#>       lq     mean  median     uq      max neval
#>  22.7715 92.30915 25.4560 45.492 5490.285   100
#>  16.4770 33.43307 18.7935 38.332  370.240   100
#>   5.2415  9.76884  6.0370  8.576  131.246   100

# larger example ----------------------------------------------------------
# define a probability density function P
P <- 1:1000000/sum(1:1000000)
# define a probability density function Q
Q <- 20:1000019/sum(20:1000019)

# combine P and Q as matrix object
x <- rbind(P,Q)

microbenchmark(
  distance(x,method = "euclidean", test.na = FALSE, mute.message = TRUE),
  dist(x,method = "euclidean"),
  euclidean(x[1 , ], x[2 , ], FALSE)
)
#> Unit: milliseconds
#>                                                                     expr
#>  distance(x, method = "euclidean", test.na = FALSE, mute.message = TRUE)
#>                                            dist(x, method = "euclidean")
#>                                         euclidean(x[1, ], x[2, ], FALSE)
#>        min        lq      mean    median        uq       max neval
#>  22.745197 25.316833 31.550059 26.339440 36.162738 84.355887   100
#>   1.850881  1.917577  2.208071  1.958871  2.449139  4.248882   100
#>  22.608342 24.857537 28.269916 25.836113 30.016983 75.630038   100
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by HajkD** [comment]
Hi Jakub,

This is awesome! I wasn't aware of this and of course we need to address this. Do you already have an idea or thought on how we can make our `philentropy` functions faster for bigger vectors and maintain its superior speed also for large vectors? Otherwise, I will of course tone down the claims in the vignette.

Many thanks!
Hajk

**Comment by Nowosad** [comment]
Sadly, I do not know how to make it faster.

**Comment by HajkD** [comment]
No problem. I will have a look at it when I have some deep focus time.

**Comment by HajkD** [comment]
Hey @Nowosad,

I finally found some time to look into this!

The issue (computational overhead) comes from the matrix sub-indexing in `euclidean(x[1, ], x[2, ], FALSE)`. When you use the vector itself (the data structure used as input in `euclidean()`) it works like a charm. Could you please confirm?

```r
P <- 1:1000000/sum(1:1000000)
# define a probability density function Q
Q <- 20:1000019/sum(20:1000019)

# combine P and Q as matrix object
x <- rbind(P,Q)

microbenchmark(
  distance(x,method = "euclidean", test.na = FALSE, mute.message = TRUE),
  dist(x,method = "euclidean"),
  euclidean(P, Q, FALSE)
)
```


```
Unit: milliseconds
                                                                    expr
 distance(x, method = "euclidean", test.na = FALSE, mute.message = TRUE)
                                           dist(x, method = "euclidean")
                                                  euclidean(P, Q, FALSE)
       min        lq      mean    median        uq       max neval
 32.297675 33.343902 34.180840 33.695681 35.049150 37.144106   100
  1.201388  2.236950  2.451605  2.654604  2.811733  3.797395   100
  1.110419  2.205261  2.181957  2.316979  2.355824  2.469391   100
```


I will change this example in the vignette.

Many thanks,
Hajk

**Comment by Nowosad** [comment]
Confirmed! Thanks.
