### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by Nowosad** [drostlab/philentropy#32]
Hi @HajkD do you have any plans to update the CRAN version of the package? I am asking because I plan to submit {supercells} (https://github.com/Nowosad/supercells) to CRAN in a near future, and it depends on philentropy 0.6.

**Comment by HajkD** [comment]
Hi @Nowosad 

I was hoping to find some time before Xmas to work on speeding up the code for large vector computations before re-submitting to CRAN, but I am happy to already submit an earlier version before if this helps.

Cheers,
Hajk

**Comment by Nowosad** [comment]
Hi @HajkD - yes, I can wait till the end of the year. Best, Jakub

**Comment by Nowosad** [comment]
Thank you, Hajk!
