### ISSUE TITLE
JSD with 0-1 bound values

### ISSUE THREAD

**Issue by Ni-Ar** [drostlab/philentropy#33]
Hi, 

I have a matrix (called `mat`) with percentages values (bound between zero and 1) and I'd like to use the `JSD` function.

To avoid the `unit = log` returning negative values I can do `JSD(x = 2^mat, unit = "log2")` but in this case what should `est.prob` be? `NULL` or `"empirical"`?

As I read from the help:
> est.prob           method to estimate probabilities from input count vectors such as non-probability vectors

Means that the estimated probabilities would be calculated on the `2^mat` input values? or the log2 transformed values (i.e. `mat` values)? I believe in this case I should use `NULL` but I'm not sure about the inner workings of the JSD function.

Thanks for clarifying,

Nicco

**Comment by HajkD** [comment]
Hi Nicco,

Yes, you got it absolutely correct:

 Estimated probabilities are calculated on the `2^mat` input values and in this case you should use `est.prob = NULL`.

I hope this helps?

Cheers,
Hajk

**Comment by Ni-Ar** [comment]
Hi @HajkD , thanks a lot for clarifying that:
```
JSD(x = 2^mat, unit = "log2", est.prob = NULL)
```
is the correct use for bounded values between zero and 1 in `mat`.
Maybe just specify in the documentation that the estimated probabilities are from the input count matrix before transformation? As the definition in the `help` "as non-probability vectors" for `est.prob`  might not be very clear for people without a solid statistical background :D 

Best,

Nicco
